/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package src;
import rx.schedulers.Schedulers;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {

        Processor.linesFromInput()
                .observeOn(Schedulers.trampoline()) //in order to run seperate thread
                .toBlocking()
                .subscribe(line ->  System.out.println(line),err -> System.out.println("error") , () -> System.out.println("hahahahaha"));
    }
}
